### ISSUE TITLE
.bat file is crashing on startup

### ISSUE THREAD

**Issue by ndstudios-admin** [alduron/JackBot#1]
Hi! 

JacBot.Bat file is crashing when I open it up.

**Comment by TheyCallMeZ** [comment]
Hi There! There should be some kind of output in the window. Paste that here and I can try to help you sort out the issue.

**Comment by TheyCallMeZ** [comment]
The two biggest things that you will need to do is open an administrative powershell console and run
`Set-ExecutionPolicy unrestricted`
and then select "A" for all

after that go into your steam library, right click on each game, go to the manage menu option, and select "Add Desktop Shortcut" 

copy and paste all of those into the links folder where JackBot is. If you have any other issues or if this resolves the issue you have please let me know.

**Comment by alduron** [comment]
No reply from @ndstudios-admin, closing issue. Logging has been added to help identify issues.
