### ISSUE TITLE
Pack2 - Looping after exit

### ISSUE THREAD

**Issue by brucbr** [alduron/JackBot#10]
When entering a game, if a user decides to quit and change game in pack 2, it exits the entire game. Seems to send one more exit key sequence than needed.

Trying to start Pack 2 will cause a loop where the game closes and reopens. Starts steam and closes and reopens and so on.

**OS:** Windows Server 2019 Standard (Desktop Experience)
**VM:** Yes (Game opened through an RDP session and then the session is redirected to console)

**Comment by alduron** [comment]
The latest update should address this issue. Bomb is the only game in this pack that follows the majority of jack pack games behavior.
