### ISSUE TITLE
User Agent is REQUIRED for http api usage

### ISSUE THREAD

**Issue by Neo-Desktop** [alduron/JackBot#14]
see: https://discord.com/developers/docs/reference#user-agent

I went ahead and added a line at the top of `JackBox.ps1`
`$UserAgent = 'DiscordBot (https://github.com/alduron/JackBot, 1.0.0)'`

And updated all `Invoke-RestMethod`  calls to include `-UserAgent $UserAgent`

This allowed the script to fetch messages from discord. Though there appears to be other problems with the script

**Comment by Sonic0810** [comment]
Did you found an fix for the problems?

**Comment by Neo-Desktop** [comment]
> Did you found an fix for the problems?

yes - did you read my comment? lmao

**Comment by Sonic0810** [comment]
I meant the other problems because you said there where other problems

**Comment by TheyCallMeZ** [comment]
PR #18  has been opened for adding this change. 

Credit to @Neo-Desktop

**Comment by alduron** [comment]
@TheyCallMeZ and @Neo-Desktop have handled the agent issue it seems.

**Comment by Neo-Desktop** [comment]
> I meant the other problems because you said there where other problems

ah not exactly - I'm not 100% sure I remember what issues I had when i was trying to make this work, but I do know this got the script to communicate with discord properly
