### ISSUE TITLE
.bat is crashing

### ISSUE THREAD

**Issue by BondiBen** [alduron/JackBot#2]
.bat didn`t work on my computer. can you give me pleace a more accurate descreption what is to do? thx

**Comment by TheyCallMeZ** [comment]
There should be some output in the window after double clicking the bat file, post it here and I can try to help you sort this out.

**Comment by TheyCallMeZ** [comment]
The two biggest things that you will need to do is open an administrative powershell console and run
`Set-ExecutionPolicy unrestricted`
and then select "A" for all

after that go into your steam library, right click on each game, go to the manage menu option, and select "Add Desktop Shortcut" 

copy and paste all of those into the links folder where JackBot is. If you have any other issues or if this resolves the issue you have please let me know.

**Comment by alduron** [comment]
No response from @BondiBen, logging has been added to help with crash issues.

**Comment by BondiBen** [comment]
Here is the error sry that i didn't answered:



### There was a problem with the installation. Please ensure it is proper JSON and retry. Exception [Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.] was thrown in [C:\JackBot-master\src\JackBot.ps1] at line [if(!(Test-Path $Script:Config.DiscordLink)){], line number [95], position [24].

**Comment by alduron** [comment]
The error you posted means that either the DiscordLink path in the config file is incorrect, the config file itself is incorrect, or the config file is not being imported properly. Please see https://github.com/alduron/JackBot#configurable-options-in-the-config-file section of the readme for details on proper config file setup.
