### ISSUE TITLE
What should happen?

### ISSUE THREAD

**Issue by NikSHiva** [alduron/JackBot#5]
What should happen after starting the JackBot.Bat? I get a command line and nothing happens (it does not give an error)

**Comment by TheyCallMeZ** [comment]
You need to set your execution policy for powershell which is mentioned in the readme 

```
No matter which machine you run it on, you need to ensure the following settings are set. These are well documented so I won't reinvent the wheel:

Ensure Windows does not sleep
(PowerShell) Set-ExecutionPolicy to unrestricted
Disable the lock screen
OPTIONAL: I set all Jackbox games to run in windowed mode, I find this helps on CPU usage and it barely makes a difference to the end users
```

**Comment by NikSHiva** [comment]
Yes, I have already set Set-ExecutionPolicy to Unrestricted. Before that, it gave an error. Now nothing is happening, maybe there is a way to check if it works or not? Is it somehow displayed in the task manager?

**Comment by TheyCallMeZ** [comment]
You may want to check to see if your Anti-Virus picked up JackBot.ps1 as IDP.ALEXA.53 
(it is a false positive)
Jotti reports it as safe
[Jotti.org scan of JackBot.ps1](https://virusscan.jotti.org/en-US/filescanjob/iyqg2ww7t9)

**Comment by TheyCallMeZ** [comment]
To answer your root question, if you double click the bat file and have your execution policy set but have not performed any configuration you should see something like this
![image](https://user-images.githubusercontent.com/321143/117006851-eb802000-acb6-11eb-9a11-07d8a351ba35.png)

**Comment by NikSHiva** [comment]
The command line opens empty, runs for a few seconds, and then closes.
Thanks for trying to help, I'll try to do everything from scratch again.

**Comment by alduron** [comment]
Just as a quick note a log file is created in the logs folder of the bot directory. Your config can change the name, but it should still appear in this folder. If you can post the log I can take a better look at it.
![image](https://user-images.githubusercontent.com/6700545/117027465-56832400-acc2-11eb-8ead-060bed319c80.png)
